define(`confMAPDEF', `-DNEWDB -DNIS')
define(`confENVDEF', `$(RPM_OPT_FLAGS) -DXDEBUG=0')
define(`confLIBS', `-lnsl')
define(`confLDOPTS', `-s')
define(`confMANOWN', `root')
define(`confMANGRP', `root')
define(`confMANMODE', `644')
define(`confMAN1SRC', `1')
define(`confMAN5SRC', `5')
define(`confMAN8SRC', `8')
APPENDDEF(`confENVDEF', -DSASL)
APPENDDEF(`conf_sendmail_LIBS', -lsasl)
APPENDDEF(`confMAPDEF', `-DLDAPMAP')
APPENDDEF(`confLIBS', `-lldap -llber')
